port 26379
bind 0.0.0.0
sentinel resolve-hostnames no
sentinel monitor mymaster 172.28.0.10 6379 1
sentinel down-after-milliseconds mymaster 3000
sentinel failover-timeout mymaster 10000
sentinel parallel-syncs mymaster 1
