// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tadka.Api.Data;

#nullable disable

namespace Tadka.Api.Migrations
{
    [DbContext(typeof(TadkaDbContext))]
    partial class TadkaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ordering")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tadka.Api.Data.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConsumedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("MessageId");

                    b.ToTable("inbox_messages", "ordering");
                });

            modelBuilder.Entity("Tadka.Api.Data.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("outbox_messages", "ordering");
                });

            modelBuilder.Entity("Tadka.Api.Data.ReadModel.MenuItemReplica", b =>
                {
                    b.Property<Guid>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PriceCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("INR");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("MenuItemId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("menu_replica", "ordering");

                    b.HasData(
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-0001-4000-8000-000000000001"),
                            IsAvailable = true,
                            Name = "Chicken Biryani",
                            PriceAmount = 299m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0001-4000-8000-000000000001"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-0002-4000-8000-000000000002"),
                            IsAvailable = true,
                            Name = "Mutton Biryani",
                            PriceAmount = 399m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0001-4000-8000-000000000001"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-0003-4000-8000-000000000003"),
                            IsAvailable = true,
                            Name = "Paneer Butter Masala",
                            PriceAmount = 249m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0001-4000-8000-000000000001"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-0004-4000-8000-000000000004"),
                            IsAvailable = true,
                            Name = "Gutti Vankaya",
                            PriceAmount = 199m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0001-4000-8000-000000000001"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-0005-4000-8000-000000000005"),
                            IsAvailable = true,
                            Name = "Chicken 65",
                            PriceAmount = 229m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0001-4000-8000-000000000001"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-0006-4000-8000-000000000006"),
                            IsAvailable = true,
                            Name = "Curd Rice",
                            PriceAmount = 99m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0001-4000-8000-000000000001"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-0007-4000-8000-000000000007"),
                            IsAvailable = true,
                            Name = "Classic Smash Burger",
                            PriceAmount = 299m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0002-4000-8000-000000000002"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-0008-4000-8000-000000000008"),
                            IsAvailable = true,
                            Name = "Truffle Special Burger",
                            PriceAmount = 449m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0002-4000-8000-000000000002"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-0009-4000-8000-000000000009"),
                            IsAvailable = true,
                            Name = "Loaded Fries",
                            PriceAmount = 199m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0002-4000-8000-000000000002"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-000a-4000-8000-000000000010"),
                            IsAvailable = true,
                            Name = "Chocolate Shake",
                            PriceAmount = 179m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0002-4000-8000-000000000002"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-000b-4000-8000-000000000011"),
                            IsAvailable = true,
                            Name = "Grilled Chicken Sandwich",
                            PriceAmount = 279m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0002-4000-8000-000000000002"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-000c-4000-8000-000000000012"),
                            IsAvailable = true,
                            Name = "Masala Dosa",
                            PriceAmount = 80m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0003-4000-8000-000000000003"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-000d-4000-8000-000000000013"),
                            IsAvailable = true,
                            Name = "Benne Masala Dosa",
                            PriceAmount = 99m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0003-4000-8000-000000000003"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-000e-4000-8000-000000000014"),
                            IsAvailable = true,
                            Name = "Idli Vada",
                            PriceAmount = 60m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0003-4000-8000-000000000003"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-000f-4000-8000-000000000015"),
                            IsAvailable = true,
                            Name = "Kesari Bath",
                            PriceAmount = 50m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0003-4000-8000-000000000003"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            MenuItemId = new Guid("b1b2c3d4-0010-4000-8000-000000000016"),
                            IsAvailable = true,
                            Name = "Filter Coffee",
                            PriceAmount = 30m,
                            PriceCurrency = "INR",
                            RestaurantId = new Guid("a1b2c3d4-0003-4000-8000-000000000003"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Tadka.Api.Data.ReadModel.RestaurantReplica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("restaurant_replica", "ordering");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-4000-8000-000000000001"),
                            IsActive = true,
                            Name = "Meghana Foods",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-4000-8000-000000000002"),
                            IsActive = true,
                            Name = "Truffles",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-4000-8000-000000000003"),
                            IsActive = true,
                            Name = "Vidyarthi Bhavan",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Tadka.Api.Domain.Delivery.DeliveryAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Available");

                    b.HasKey("Id");

                    b.ToTable("agents", "delivery");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1b2c3d4-0001-4000-8000-000000000001"),
                            Name = "Ramesh Kumar",
                            Phone = "+919876543210",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("d1b2c3d4-0002-4000-8000-000000000002"),
                            Name = "Suresh Patel",
                            Phone = "+919876543211",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("Tadka.Api.Domain.Delivery.DeliveryAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Assigned");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("assignments", "delivery");
                });

            modelBuilder.Entity("Tadka.Api.Domain.Orders.IdempotencyKey", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Key");

                    b.ToTable("idempotency_keys", "ordering");
                });

            modelBuilder.Entity("Tadka.Api.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Created");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_orders_created_at");

                    b.HasIndex("CustomerId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_orders_customer_id_created_at");

                    b.ToTable("orders", "ordering");
                });

            modelBuilder.Entity("Tadka.Api.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("MenuItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("order_items", "ordering");
                });

            modelBuilder.Entity("Tadka.Api.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("OwnedRestaurantId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Customer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Tadka.Api.Domain.Users.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_addresses", "identity");
                });

            modelBuilder.Entity("Tadka.Api.Domain.Delivery.DeliveryAgent", b =>
                {
                    b.OwnsOne("Tadka.Api.Domain.ValueObjects.GeoLocation", "CurrentLocation", b1 =>
                        {
                            b1.Property<Guid>("DeliveryAgentId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("current_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("current_longitude");

                            b1.HasKey("DeliveryAgentId");

                            b1.ToTable("agents", "delivery");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryAgentId");

                            b1.HasData(
                                new
                                {
                                    DeliveryAgentId = new Guid("d1b2c3d4-0001-4000-8000-000000000001"),
                                    Latitude = 12.9352,
                                    Longitude = 77.624499999999998
                                },
                                new
                                {
                                    DeliveryAgentId = new Guid("d1b2c3d4-0002-4000-8000-000000000002"),
                                    Latitude = 12.978400000000001,
                                    Longitude = 77.640799999999999
                                });
                        });

                    b.Navigation("CurrentLocation");
                });

            modelBuilder.Entity("Tadka.Api.Domain.Delivery.DeliveryAssignment", b =>
                {
                    b.HasOne("Tadka.Api.Domain.Delivery.DeliveryAgent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tadka.Api.Domain.Orders.Order", b =>
                {
                    b.OwnsOne("Tadka.Api.Domain.ValueObjects.Address", "DeliveryAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("delivery_address_city");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("delivery_latitude");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("delivery_address_line1");

                            b1.Property<string>("Line2")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("delivery_address_line2");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("delivery_longitude");

                            b1.Property<string>("Pincode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("delivery_address_pincode");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders", "ordering");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Tadka.Api.Domain.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("INR")
                                .HasColumnName("currency");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders", "ordering");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("DeliveryAddress")
                        .IsRequired();

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("Tadka.Api.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("Tadka.Api.Domain.Orders.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Tadka.Api.Domain.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("OrderItemId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("unit_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("INR")
                                .HasColumnName("currency");

                            b1.HasKey("OrderItemId");

                            b1.ToTable("order_items", "ordering");

                            b1.WithOwner()
                                .HasForeignKey("OrderItemId");
                        });

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("Tadka.Api.Domain.Users.UserAddress", b =>
                {
                    b.HasOne("Tadka.Api.Domain.Users.User", null)
                        .WithMany("SavedAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Tadka.Api.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("UserAddressId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("city");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("line1");

                            b1.Property<string>("Line2")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("line2");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.Property<string>("Pincode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("pincode");

                            b1.HasKey("UserAddressId");

                            b1.ToTable("user_addresses", "identity");

                            b1.WithOwner()
                                .HasForeignKey("UserAddressId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Tadka.Api.Domain.Orders.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tadka.Api.Domain.Users.User", b =>
                {
                    b.Navigation("SavedAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
