// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tadka.Restaurant.Api.Data;

#nullable disable

namespace Tadka.Restaurant.Api.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20260606123236_Day13OutboxTraceParent")]
    partial class Day13OutboxTraceParent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("restaurant")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tadka.Restaurant.Api.Domain.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVeg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("RestaurantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("menu_items", "restaurant");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1b2c3d4-0001-4000-8000-000000000001"),
                            Category = "Biryani",
                            Description = "Hyderabadi-style dum biryani with tender chicken",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Chicken Biryani",
                            RestaurantId = new Guid("a1b2c3d4-0001-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-4000-8000-000000000002"),
                            Category = "Biryani",
                            Description = "Slow-cooked mutton dum biryani with salan",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Mutton Biryani",
                            RestaurantId = new Guid("a1b2c3d4-0001-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0003-4000-8000-000000000003"),
                            Category = "Main Course",
                            Description = "Creamy paneer in rich tomato gravy",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Paneer Butter Masala",
                            RestaurantId = new Guid("a1b2c3d4-0001-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0004-4000-8000-000000000004"),
                            Category = "Main Course",
                            Description = "Stuffed brinjal curry, Andhra style",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Gutti Vankaya",
                            RestaurantId = new Guid("a1b2c3d4-0001-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0005-4000-8000-000000000005"),
                            Category = "Starters",
                            Description = "Spicy deep-fried chicken, Hyderabadi classic",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Chicken 65",
                            RestaurantId = new Guid("a1b2c3d4-0001-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0006-4000-8000-000000000006"),
                            Category = "Rice",
                            Description = "Comfort food with tempered curd rice",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Curd Rice",
                            RestaurantId = new Guid("a1b2c3d4-0001-4000-8000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0007-4000-8000-000000000007"),
                            Category = "Burgers",
                            Description = "Double-patty smash burger with house sauce",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Classic Smash Burger",
                            RestaurantId = new Guid("a1b2c3d4-0002-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0008-4000-8000-000000000008"),
                            Category = "Burgers",
                            Description = "Signature burger with truffle mayo and caramelized onions",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Truffle Special Burger",
                            RestaurantId = new Guid("a1b2c3d4-0002-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0009-4000-8000-000000000009"),
                            Category = "Sides",
                            Description = "Crispy fries with cheese, jalapenos, and sour cream",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Loaded Fries",
                            RestaurantId = new Guid("a1b2c3d4-0002-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-000a-4000-8000-000000000010"),
                            Category = "Beverages",
                            Description = "Thick chocolate milkshake with whipped cream",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Chocolate Shake",
                            RestaurantId = new Guid("a1b2c3d4-0002-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-000b-4000-8000-000000000011"),
                            Category = "Sandwiches",
                            Description = "Grilled chicken breast with lettuce and garlic aioli",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Grilled Chicken Sandwich",
                            RestaurantId = new Guid("a1b2c3d4-0002-4000-8000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-000c-4000-8000-000000000012"),
                            Category = "Dosa",
                            Description = "Crispy dosa with spiced potato filling",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Masala Dosa",
                            RestaurantId = new Guid("a1b2c3d4-0003-4000-8000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-000d-4000-8000-000000000013"),
                            Category = "Dosa",
                            Description = "Butter-roasted dosa, Karnataka specialty",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Benne Masala Dosa",
                            RestaurantId = new Guid("a1b2c3d4-0003-4000-8000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-000e-4000-8000-000000000014"),
                            Category = "Breakfast",
                            Description = "Steamed idli with crispy medu vada and sambar",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Idli Vada",
                            RestaurantId = new Guid("a1b2c3d4-0003-4000-8000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-000f-4000-8000-000000000015"),
                            Category = "Desserts",
                            Description = "Sweet semolina halwa with ghee and cashews",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Kesari Bath",
                            RestaurantId = new Guid("a1b2c3d4-0003-4000-8000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0010-4000-8000-000000000016"),
                            Category = "Beverages",
                            Description = "South Indian filter coffee, strong and frothy",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Filter Coffee",
                            RestaurantId = new Guid("a1b2c3d4-0003-4000-8000-000000000003")
                        });
                });

            modelBuilder.Entity("Tadka.Restaurant.Api.Domain.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("outbox_messages", "restaurant");
                });

            modelBuilder.Entity("Tadka.Restaurant.Api.Domain.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvgPrepTimeMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("restaurants", "restaurant");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-4000-8000-000000000001"),
                            AvgPrepTimeMinutes = 25,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Meghana Foods"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-4000-8000-000000000002"),
                            AvgPrepTimeMinutes = 30,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Truffles"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-4000-8000-000000000003"),
                            AvgPrepTimeMinutes = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Vidyarthi Bhavan"
                        });
                });

            modelBuilder.Entity("Tadka.Restaurant.Api.Domain.MenuItem", b =>
                {
                    b.HasOne("Tadka.Restaurant.Api.Domain.Restaurant", null)
                        .WithMany("Menu")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Tadka.Restaurant.Api.Domain.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("MenuItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasDefaultValue("INR")
                                .HasColumnName("currency");

                            b1.HasKey("MenuItemId");

                            b1.ToTable("menu_items", "restaurant");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemId");

                            b1.HasData(
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-0001-4000-8000-000000000001"),
                                    Amount = 299m,
                                    Currency = "INR"
                                },
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-0002-4000-8000-000000000002"),
                                    Amount = 399m,
                                    Currency = "INR"
                                },
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-0003-4000-8000-000000000003"),
                                    Amount = 249m,
                                    Currency = "INR"
                                },
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-0004-4000-8000-000000000004"),
                                    Amount = 199m,
                                    Currency = "INR"
                                },
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-0005-4000-8000-000000000005"),
                                    Amount = 229m,
                                    Currency = "INR"
                                },
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-0006-4000-8000-000000000006"),
                                    Amount = 99m,
                                    Currency = "INR"
                                },
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-0007-4000-8000-000000000007"),
                                    Amount = 299m,
                                    Currency = "INR"
                                },
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-0008-4000-8000-000000000008"),
                                    Amount = 449m,
                                    Currency = "INR"
                                },
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-0009-4000-8000-000000000009"),
                                    Amount = 199m,
                                    Currency = "INR"
                                },
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-000a-4000-8000-000000000010"),
                                    Amount = 179m,
                                    Currency = "INR"
                                },
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-000b-4000-8000-000000000011"),
                                    Amount = 279m,
                                    Currency = "INR"
                                },
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-000c-4000-8000-000000000012"),
                                    Amount = 80m,
                                    Currency = "INR"
                                },
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-000d-4000-8000-000000000013"),
                                    Amount = 99m,
                                    Currency = "INR"
                                },
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-000e-4000-8000-000000000014"),
                                    Amount = 60m,
                                    Currency = "INR"
                                },
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-000f-4000-8000-000000000015"),
                                    Amount = 50m,
                                    Currency = "INR"
                                },
                                new
                                {
                                    MenuItemId = new Guid("b1b2c3d4-0010-4000-8000-000000000016"),
                                    Amount = 30m,
                                    Currency = "INR"
                                });
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("Tadka.Restaurant.Api.Domain.Restaurant", b =>
                {
                    b.OwnsOne("Tadka.Restaurant.Api.Domain.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("address_city");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line1");

                            b1.Property<string>("Line2")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("address_line2");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.Property<string>("Pincode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("address_pincode");

                            b1.HasKey("RestaurantId");

                            b1.ToTable("restaurants", "restaurant");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId");

                            b1.HasData(
                                new
                                {
                                    RestaurantId = new Guid("a1b2c3d4-0001-4000-8000-000000000001"),
                                    City = "Bangalore",
                                    Latitude = 12.9352,
                                    Line1 = "124, Near Forum Mall",
                                    Line2 = "Koramangala 5th Block",
                                    Longitude = 77.624499999999998,
                                    Pincode = "560095"
                                },
                                new
                                {
                                    RestaurantId = new Guid("a1b2c3d4-0002-4000-8000-000000000002"),
                                    City = "Bangalore",
                                    Latitude = 12.978400000000001,
                                    Line1 = "96, 12th Main Road",
                                    Line2 = "HAL 2nd Stage, Indiranagar",
                                    Longitude = 77.640799999999999,
                                    Pincode = "560038"
                                },
                                new
                                {
                                    RestaurantId = new Guid("a1b2c3d4-0003-4000-8000-000000000003"),
                                    City = "Bangalore",
                                    Latitude = 12.945399999999999,
                                    Line1 = "32, Gandhi Bazaar Main Road",
                                    Line2 = "Basavanagudi",
                                    Longitude = 77.572599999999994,
                                    Pincode = "560004"
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Tadka.Restaurant.Api.Domain.Restaurant", b =>
                {
                    b.Navigation("Menu");
                });
#pragma warning restore 612, 618
        }
    }
}
